# Generated by Django 3.1.4 on 2021-12-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('article', models.CharField(max_length=1000)),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
