# Generated by Django 3.1.4 on 2022-01-15 14:59

import Library.extra
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20220115_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=Library.extra.ContentTypeRestrictedFileField(blank=True, max_length=250, null=True, upload_to='LibRead/images/'),
        ),
    ]
